//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogWebPage.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int ID { get; set; }
        public string CoverImage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Title { get; set; }
        public string ContentImage1 { get; set; }
        public string Description1 { get; set; }
        public string ContentImage2 { get; set; }
        public string Description2 { get; set; }
        public string ContentImage3 { get; set; }
        public string Description3 { get; set; }
        public string ContentImage4 { get; set; }
        public string Description4 { get; set; }
        public string ContentImage5 { get; set; }
        public string Description5 { get; set; }
        public string ContentImage6 { get; set; }
        public string Description6 { get; set; }
    }
}
